services:

    getmail:
      image: cb/getmail
      build: ./Dockerfiles
      pull_policy: never
      environment:
        - TZ=${TZ}
      volumes:
        - ./conf/settings.ini:/app/settings.ini:ro
      restart: always
      mem_limit: 100m
      mem_reservation: 20m
      networks:
        network-getmail:

    #optional
    clamd:
      image: clamav/clamav:stable
      expose:
        - "3310"
      volumes:
        - clam_db:/var/lib/clamav
      restart: always

#optional
volumes:
  clam_db:

#docker network create --driver=bridge --ipv6 --subnet=fdcb:9c90:23:11::/64 --gateway=fdcb:9c90:23:11::1 --subnet=172.23.11.0/24 --gateway=172.23.11.1 -o "com.docker.network.bridge.name"="br-getmail" network-getmail     
networks:
  network-getmail:
    external: true
